;;; rotate-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from rotate.el

(autoload 'rotate-layout "rotate" nil t)
(autoload 'rotate-window "rotate" nil t)
(autoload 'rotate:even-horizontal "rotate" nil t)
(autoload 'rotate:even-vertical "rotate" nil t)
(autoload 'rotate:main-horizontal "rotate" nil t)
(autoload 'rotate:main-vertical "rotate" nil t)
(autoload 'rotate:tiled "rotate" nil t)
(register-definition-prefixes "rotate" '("rotate"))

;;; End of scraped data

(provide 'rotate-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; rotate-autoloads.el ends here
