;;; rotate-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from rotate.el

(autoload 'rotate-layout "rotate" "\
Switch to the next layout in `rotate-functions'." t)
(autoload 'rotate-window "rotate" "\
Rotate buffers across the windows of the selected frame." t)
(autoload 'rotate-even-horizontal "rotate" "\
Spread windows evenly from left to right." t)
(autoload 'rotate-even-vertical "rotate" "\
Spread windows evenly from top to bottom." t)
(autoload 'rotate-main-horizontal "rotate" "\
Put one main window on top, the rest spread horizontally below." t)
(autoload 'rotate-main-vertical "rotate" "\
Put one main window on the left, the rest spread vertically on the right." t)
(autoload 'rotate-tiled "rotate" "\
Arrange windows in a tiled grid." t)
(register-definition-prefixes "rotate" '("rotate-"))

;;; End of scraped data

(provide 'rotate-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; rotate-autoloads.el ends here
